import { NextRequest, NextResponse } from "next/server";
import archiver from "archiver";
import { rateLimit, validateUrl } from "@/lib/utils/security";

export async function POST(req: NextRequest) {
  try {
    const ip = req.headers.get("x-forwarded-for") || "anonymous";
    const limited = rateLimit(ip, 10, 60000);
    if (limited) return limited;

    const { template, images, productTitle } = await req.json();

    if (!template) {
      return NextResponse.json(
        { error: "Template data is required" },
        { status: 400 }
      );
    }

    const archive = archiver("zip", { zlib: { level: 9 } });
    const chunks: Buffer[] = [];

    archive.on("data", (chunk: Buffer) => chunks.push(chunk));

    // Add template JSON
    const templateJson = JSON.stringify(template, null, 2);
    const comment = `/*\n * ------------------------------------------------------------\n * IMPORTANT: The contents of this file are auto-generated.\n *\n * This file may be updated by the Shopify admin theme editor\n * or related systems. Please exercise caution as any changes\n * made to this file may be overwritten.\n * ------------------------------------------------------------\n */\n`;
    archive.append(comment + templateJson, {
      name: "templates/product.generated.json",
    });

    // Add README
    const readme = `# Product Page Export - ${productTitle || "Product"}\n\nGenerated by PageForge\n\n## How to import into Shopify:\n\n1. Go to your Shopify Admin > Online Store > Themes\n2. Click "Edit code" on your current theme\n3. Navigate to Templates folder\n4. Upload or paste the content of product.generated.json\n5. Upload images from the assets/ folder to your Shopify Files\n6. Assign the template to your product\n\n## Files included:\n- templates/product.generated.json - The Shopify product template\n- assets/ - Product images (if downloaded)\n`;
    archive.append(readme, { name: "README.md" });

    // Download images with validation and timeout
    if (images && Array.isArray(images)) {
      const safeImages = images
        .slice(0, 10)
        .filter((img: { url: string }) => {
          const check = validateUrl(img.url);
          return check.valid;
        });

      const imagePromises = safeImages.map(
        async (img: { url: string; alt?: string }, index: number) => {
          try {
            const controller = new AbortController();
            const timeout = setTimeout(() => controller.abort(), 8000);
            const response = await fetch(img.url, {
              headers: {
                "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
              },
              signal: controller.signal,
            });
            clearTimeout(timeout);

            if (response.ok) {
              const arrayBuffer = await response.arrayBuffer();
              // Max 5MB per image
              if (arrayBuffer.byteLength <= 5 * 1024 * 1024) {
                const buffer = Buffer.from(arrayBuffer);
                const ext = getImageExtension(img.url);
                archive.append(buffer, {
                  name: `assets/product-image-${index + 1}.${ext}`,
                });
              }
            }
          } catch {
            // Skip failed images silently
          }
        }
      );
      await Promise.all(imagePromises);
    }

    await archive.finalize();

    const zipBuffer = Buffer.concat(chunks);
    const slug = (productTitle || "product")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .slice(0, 50);

    return new NextResponse(zipBuffer, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="pageforge-${slug}.zip"`,
      },
    });
  } catch (error) {
    console.error("Download error:", error);
    return NextResponse.json(
      { error: "Failed to create download" },
      { status: 500 }
    );
  }
}

function getImageExtension(url: string): string {
  const match = url.match(/\.(jpg|jpeg|png|gif|webp|avif)/i);
  return match ? match[1].toLowerCase() : "jpg";
}
